VSC 1
UVASGD/sgd-docs pull request #9
Opened 2017-07-06 04:18 UTC by zsd4yr

2017-08-14 00:09 UTC, ferociouself commented on source/guide.md
> +For the rest of this guide, I'll be talking in terms of Github or Git, which is a single VSC among many. Many of the ideas of Git are shared among others, so this should simply this tutorial without
simply -> simplify

2017-08-14 00:12 UTC, ferociouself commented on source/guide.md
> +It will be up to each project to decide which workflow is best for it. Almost always, an agreed-upon structure on each team is critical, but the exact nature of that structure is up to the needs and
think -> thing

2017-08-14 00:53 UTC, ferociouself commented on source/guide.md
> +##### Pair Programming
I kind of see how this relates to the heading directly above it, but I'm not sure this belongs in the Source Control article. The two above relate to VSC due to their integration with pull requests and branching, but pair programming seems to be a bit unrelated to the larger topic.

2017-08-14 00:56 UTC, ferociouself commented on source/guide.md
> +* git grep -> Lets you search through your trees of content for words and phrases. Example: git grep "www.siteground.com" -- *.php
You might need to escape that "*.php", it looks like it might cause some issues on the markup end.

2017-08-14 00:59 UTC, ferociouself requested changes
Some minor spelling corrections, and also a comment about the relevance of discussing Pair Programming in this article.

2017-08-15 01:14 UTC, zsd4yr commented on source/guide.md
> +For the rest of this guide, I'll be talking in terms of Github or Git, which is a single VSC among many. Many of the ideas of Git are shared among others, so this should simply this tutorial without
done

2017-08-15 01:15 UTC, zsd4yr commented on source/guide.md
> +It will be up to each project to decide which workflow is best for it. Almost always, an agreed-upon structure on each team is critical, but the exact nature of that structure is up to the needs and
done

2017-08-15 01:15 UTC, zsd4yr commented on source/guide.md
> +##### Pair Programming
done

2017-08-15 01:16 UTC, zsd4yr commented
@ferociouself you made an earlier comment about the php?

2017-08-15 04:40 UTC, ferociouself commented
I don't remember anything about php, so I'm gonna go ahead and merge this in haha

2017-08-15 04:40 UTC, merged